In [1]:
import pandas as pd
import numpy as np


pivoted_data_path = 'C:/Users/klbal/Desktop/Internship #2/pivoted_output.txt'

pivoted_data = pd.read_csv(pivoted_data_path, delimiter='\t')


print(pivoted_data[["Chlamy107", "Chlamy123"]])

     Chlamy107  Chlamy123
0     0.479167    0.00000
1     0.312500    0.12500
2     0.208333    0.06250
3     0.250000    0.12500
4     0.333333    0.21875
..         ...        ...
105   0.000000    0.06250
106   0.000000    0.03125
107   0.000000    0.03125
108   0.000000    0.06250
109   0.000000    0.03125

[110 rows x 2 columns]


In [2]:

# set bakteria names -> later remove by iteration
bakti_1 = "Chlamy107"
bakti_2 = "Chlamy123"

# extract values
bakti_1_val = pivoted_data[bakti_1].values
bakti_2_val = pivoted_data[bakti_2].values

joint_counts = np.histogram2d(bakti_1_val, bakti_2_val, bins=10)[0]

print(joint_counts)

joint_probs = joint_counts / np.sum(joint_counts)

marginal_probs_bakti_1 = np.sum(joint_probs, axis=1)

marginal_probs_bakti_2 = np.sum(joint_probs, axis=0)

print(marginal_probs_bakti_1)
print(marginal_probs_bakti_2)



[[64. 12.  4.  1.  2.  0.  0.  0.  0.  2.]
 [ 5.  1.  2.  0.  1.  0.  0.  0.  0.  0.]
 [ 2.  3.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  2.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[0.77272727 0.08181818 0.05454545 0.03636364 0.01818182 0.00909091
 0.01818182 0.         0.         0.00909091]
[0.7        0.15454545 0.09090909 0.00909091 0.02727273 0.
 0.         0.         0.         0.01818182]


In [3]:
#test
# set bakteria names -> later remove by iteration
bakti_2 = "Chlamy107"
bakti_1 = "Chlamy123"

# extract values
bakti_1_val = pivoted_data[bakti_1].values
bakti_2_val = pivoted_data[bakti_2].values

joint_counts = np.histogram2d(bakti_1_val, bakti_2_val, bins=20)[0]

print(joint_counts)

joint_probs = joint_counts / np.sum(joint_counts)

marginal_probs_bakti_1 = np.sum(joint_probs, axis=1)

marginal_probs_bakti_2 = np.sum(joint_probs, axis=0)

print(marginal_probs_bakti_1)
print(marginal_probs_bakti_2)


[[41.  3.  2.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.]
 [20.  0.  2.  1.  1.  1.  2.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [ 9.  2.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 1.  0.  0.  0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [ 2.  0.  0.  1.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 2.  0.  0.  1.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

In [4]:
# calculate MI

mutual_info = 0

for i in range(joint_counts.shape[0]):
    
    for j in range(joint_counts.shape[1]):
        
        if joint_probs[i, j] > 0:

            if marginal_probs_bakti_1[i] > 0 and marginal_probs_bakti_1[j] > 0:
                
                mutual_info += joint_probs[i, j] * np.log2(joint_probs[i, j] / (marginal_probs_bakti_1[i] * marginal_probs_bakti_1[j]))

print(mutual_info)


0.8223915238521075


In [5]:
# create funktion

def calc_MI(bakti_1, bakti_2, amount_bins):

    bakti_1_val = pivoted_data[bakti_1].values
    bakti_2_val = pivoted_data[bakti_2].values

    joint_counts = np.histogram2d(bakti_1_val, bakti_2_val, bins = amount_bins)[0]
    joint_probs = joint_counts / np.sum(joint_counts)

    marginal_probs_bakti_1 = np.sum(joint_probs, axis=1)
    marginal_probs_bakti_2 = np.sum(joint_probs, axis=0)

    mutual_info = 0

    for i in range(joint_counts.shape[0]):
        
        for j in range(joint_counts.shape[1]):
            
            if joint_probs[i, j] > 0:

                if marginal_probs_bakti_2[i] > 0 and marginal_probs_bakti_1[j] > 0:
                    
                    mutual_info += joint_probs[i, j] * np.log2(joint_probs[i, j] / (marginal_probs_bakti_2[i] * marginal_probs_bakti_1[j]))

    return(mutual_info)

In [6]:
all_baktis = pivoted_data.columns

print(all_baktis)

Index(['Chlamy107', 'Chlamy123', 'Chlamy125', 'Chlamy165', 'Chlamy19',
       'Chlamy23', 'Chlamy24', 'Chlamy26', 'Chlamy28', 'Chlamy43', 'Chlamy44',
       'Chlamy45', 'Chlamy6', 'Chlamy7', 'Chlamy74', 'Chlamy75', 'Chlamy77',
       'Chlamy8', 'Chlamy88', 'Chlamy90'],
      dtype='object')


In [7]:
import pandas as pd
import itertools



# create funktion

def calc_MI(bakti_1, bakti_2, amount_bins):

    bakti_1_val = pivoted_data[bakti_1].values
    bakti_2_val = pivoted_data[bakti_2].values

    joint_counts = np.histogram2d(bakti_1_val, bakti_2_val, bins = amount_bins)[0]
    joint_probs = joint_counts / np.sum(joint_counts)

    marginal_probs_bakti_1 = np.sum(joint_probs, axis=1)
    marginal_probs_bakti_2 = np.sum(joint_probs, axis=0)

    mutual_info = 0

    for i in range(joint_counts.shape[0]):
        
        for j in range(joint_counts.shape[1]):
            
            if joint_probs[i, j] > 0:

                if marginal_probs_bakti_2[i] > 0 and marginal_probs_bakti_1[j] > 0:
                    
                    mutual_info += joint_probs[i, j] * np.log2(joint_probs[i, j] / (marginal_probs_bakti_2[i] * marginal_probs_bakti_1[j]))

    return(mutual_info)


# create empty matrix
num_bacteria = len(all_baktis)
MI_matrix = [[0] * num_bacteria for _ in range(num_bacteria)]

amount_bins = 10

# fill with MI values
for i, name1 in enumerate(all_baktis):
    for j, name2 in enumerate(all_baktis):
        if i == j:
            continue
        MI = calc_MI(name1, name2, amount_bins)
        MI_matrix[i][j] = MI

# Erstelle einen DataFrame aus der Matrix und füge die Bakteriennamen als Index und Spaltennamen hinzu
df = pd.DataFrame(MI_matrix, columns=all_baktis, index=all_baktis)

# Gib den DataFrame aus
print(df)


           Chlamy107  Chlamy123  Chlamy125  Chlamy165  Chlamy19  Chlamy23  \
Chlamy107   0.000000   0.301376   0.633909   1.901828  0.061471  0.685051   
Chlamy123   0.301376   0.000000   0.396263   1.298189  0.109780  0.373455   
Chlamy125   0.633909   0.396263   0.000000   1.288933  0.415061  0.446918   
Chlamy165   1.901828   1.298189   1.288933   0.000000  0.962163  0.933915   
Chlamy19    0.061471   0.109780   0.415061   0.962163  0.000000  0.270246   
Chlamy23    0.685051   0.373455   0.446918   0.933915  0.270246  0.000000   
Chlamy24    0.484294   0.686392   1.315429   2.615585  0.309317  1.375565   
Chlamy26    0.618277   0.453633   1.015002   2.036944  0.215069  0.816257   
Chlamy28    2.966617   2.123548   2.472504   0.939559  1.081238  1.706753   
Chlamy43    0.430348   0.825309   1.409842   1.817025  0.328825  1.371630   
Chlamy44    0.535212   0.843893   1.350663   3.095730  0.354582  1.597732   
Chlamy45    3.032887   2.245560   2.178195   1.351707  1.991177  1.639270   